// src/client/components/MiniGameBoard.tsx
import { For } from 'solid-js';
import { PB_GameBoardType } from '../../common/pb';
import { gameBoardTypeToCSSClassName } from '../helpers';
import styles from './MiniGameBoard.module.css';

export function MiniGameBoard(props: { gameBoard: PB_GameBoardType[][]; cellSize: number }) {
  return (
    <table
      class={styles.root}
      style={{ width: `${props.cellSize * 12 + 1}px`, height: `${props.cellSize * 9 + 1}px` }}
    >
      <tbody>
        <For each={props.gameBoard}>
          {(gameBoardRow) => (
            <tr>
              <For each={gameBoardRow}>
                {(gameBoardType) => <td class={gameBoardTypeToCSSClassName.get(gameBoardType)} />}
              </For>
            </tr>
          )}
        </For>
      </tbody>
    </table>
  );
}

// src/lib/MiniGameBoard.svelte
<svelte:options immutable />

<script lang="ts">
	import type { PB_GameBoardType } from '$common/pb';
	import { gameBoardTypeToCSSClassName } from './helpers';

	export let gameBoard: PB_GameBoardType[][];
	export let cellSize: number;
</script>

<table style="width: {cellSize * 12 + 1}px; height: {cellSize * 9 + 1}px">
	<tbody>
		{#each gameBoard as gameBoardRow}
			<tr>
				{#each gameBoardRow as gameBoardType}
					<td class={gameBoardTypeToCSSClassName.get(gameBoardType)} />
				{/each}
			</tr>
		{/each}
	</tbody>
</table>

<style>
	table {
		border-collapse: collapse;
		table-layout: fixed;
	}

	td {
		border: 1px solid #f6f4f2;
	}
</style>
