// src/client/components/PurchaseShares.tsx
import {
  batch,
  createEffect,
  createMemo,
  createSignal,
  Index,
  type JSX,
  on,
  onMount,
} from 'solid-js';
import { type PB_GameBoardType } from '../../common/pb.js';
import stylesApp from '../App.module.css';
import {
  allChains,
  gameBoardTypeToHotelInitial,
  keyboardEventCodeToGameBoardType,
} from '../helpers.js';
import { KEY_SHIFT, type ProcessMyKeyboardEventRef } from '../myKeyboardEvents.js';
import { gameBoardTypeToCSSClassName } from '../styleHelpers.js';
import styles from './PurchaseShares.module.css';

export function PurchaseShares(props: {
  ref: (ref: ProcessMyKeyboardEventRef) => void;
  scoreBoardAvailable: number[];
  scoreBoardPrice: number[];
  cash: number;
  buttonSize: number;
  onSharesPurchased: (chains: PB_GameBoardType[], endGame: boolean) => void;
}) {
  const [availableButtonStatuses, setAvailableButtonStatuses] = createSignal<
    AvailableButtonStatus[]
  >([]);
  const [costTotal, setCostTotal] = createSignal(0);
  const [costLeft, setCostLeft] = createSignal(0);
  const [cart, setCart] = createSignal<(number | null)[]>([null, null, null]);
  const [endGame, setEndGame] = createSignal(false);

  createEffect(
    on([() => props.scoreBoardAvailable, () => props.scoreBoardPrice, () => props.cash], () =>
      updateValues([null, null, null]),
    ),
  );

  function updateValues(newCart: (number | null)[]) {
    const chainToNumSharesInCart = new Map<number, number>();
    let newCostTotal = 0;
    let numItemsInCart = 0;
    for (let i = 0; i < newCart.length; i++) {
      const chain = newCart[i];
      if (chain !== null) {
        chainToNumSharesInCart.set(chain, (chainToNumSharesInCart.get(chain) ?? 0) + 1);
        newCostTotal += props.scoreBoardPrice[chain];
        numItemsInCart++;
      }
    }
    const newCostLeft = props.cash - newCostTotal;

    const newAvailableButtonStatuses = allChains.map((chain) => {
      const numAvailable = props.scoreBoardAvailable[chain];
      const price = props.scoreBoardPrice[chain];

      if (price > 0 && numAvailable > 0) {
        const numRemaining = numAvailable - (chainToNumSharesInCart.get(chain) ?? 0);
        const canAddThis = numItemsInCart < 3 && numRemaining > 0 && price <= newCostLeft;

        return canAddThis ? AvailableButtonStatus.Enabled : AvailableButtonStatus.Disabled;
      } else {
        return AvailableButtonStatus.Invisible;
      }
    });

    batch(() => {
      setAvailableButtonStatuses(newAvailableButtonStatuses);
      setCostTotal(newCostTotal);
      setCostLeft(newCostLeft);
      setCart(newCart);
    });
  }

  const buttonStyle = createMemo<JSX.CSSProperties>(() => ({
    width: `${props.buttonSize}px`,
    height: `${props.buttonSize}px`,
  }));

  const cartButtonStyle = createMemo<JSX.CSSProperties>(() => ({
    width: `${Math.floor(props.buttonSize * (4 / 3))}px`,
    height: `${props.buttonSize}px`,
  }));

  function handleOK() {
    const chains: PB_GameBoardType[] = [];
    const c = cart();
    for (let i = 0; i < c.length; i++) {
      const entry = c[i];
      if (entry !== null) {
        chains.push(entry);
      }
    }

    props.onSharesPurchased(chains, endGame());
  }

  const availableButtons: HTMLInputElement[] = new Array(allChains.length);
  const cartButtons: HTMLInputElement[] = new Array(3);
  let endGameCheckbox!: HTMLInputElement;
  let okButton!: HTMLInputElement;
  onMount(() => {
    props.ref({
      processMyKeyboardEvent: (myKeyboardEvent) => {
        const gameBoardType = keyboardEventCodeToGameBoardType.get(myKeyboardEvent.code);

        if (myKeyboardEvent.modifiers === 0) {
          if (gameBoardType !== undefined) {
            const button = availableButtons[gameBoardType];
            button.focus();
            button.click();
          } else if (
            myKeyboardEvent.code === 'Backspace' ||
            myKeyboardEvent.code === 'Delete' ||
            myKeyboardEvent.code === 'NumpadSubtract'
          ) {
            const c = cart();
            for (let i = c.length - 1; i >= 0; i--) {
              if (c[i] !== null) {
                const button = cartButtons[i];
                button.focus();
                button.click();
                break;
              }
            }
          } else if (myKeyboardEvent.code === 'KeyE' || myKeyboardEvent.code === 'NumpadMultiply') {
            endGameCheckbox.focus();
            endGameCheckbox.click();
          } else if (
            myKeyboardEvent.code === 'KeyO' ||
            myKeyboardEvent.code === 'Digit0' ||
            myKeyboardEvent.code === 'Numpad0' ||
            myKeyboardEvent.code === 'Digit8' ||
            myKeyboardEvent.code === 'Numpad8'
          ) {
            okButton.focus();
          }
        } else if (myKeyboardEvent.modifiers === KEY_SHIFT) {
          if (gameBoardType !== undefined) {
            const c = cart();
            for (let i = c.length - 1; i >= 0; i--) {
              if (c[i] === gameBoardType) {
                const button = cartButtons[i];
                button.focus();
                button.click();
                break;
              }
            }
          }
        }
      },
    });
  });

  return (
    <div class={styles.root} style={{ 'font-size': `${Math.floor(props.buttonSize * 0.4)}px` }}>
      <div class={styles.topRow}>
        <fieldset>
          <legend>Available</legend>
          <Index each={availableButtonStatuses()}>
            {(availableButtonStatus, chain) => (
              <>
                <input
                  ref={availableButtons[chain]}
                  type="button"
                  classList={{
                    [stylesApp.hotelButton]: true,
                    [gameBoardTypeToCSSClassName.get(chain)!]: true,
                    [stylesApp.invisible]:
                      availableButtonStatus() === AvailableButtonStatus.Invisible,
                  }}
                  disabled={availableButtonStatus() !== AvailableButtonStatus.Enabled}
                  style={buttonStyle()}
                  value={gameBoardTypeToHotelInitial.get(chain)}
                  onClick={() => {
                    const c = cart();
                    for (let i = 0; i < c.length; i++) {
                      if (c[i] === null) {
                        const newCart = [...c];
                        newCart[i] = chain;
                        updateValues(newCart);
                        break;
                      }
                    }
                  }}
                />
              </>
            )}
          </Index>
        </fieldset>{' '}
        <fieldset>
          <legend>Cost</legend>
          <table>
            <tbody>
              <tr>
                <td>Total</td>
                <td>{costTotal() * 100}</td>
              </tr>
              <tr>
                <td>Left</td>
                <td>{costLeft() * 100}</td>
              </tr>
            </tbody>
          </table>
        </fieldset>
      </div>
      <div>
        <fieldset>
          <legend>Cart</legend>
          <Index each={cart()}>
            {(chain, i) => (
              <>
                <input
                  ref={cartButtons[i]}
                  type="button"
                  classList={{
                    [stylesApp.hotelButton]: true,
                    [gameBoardTypeToCSSClassName.get(chain() ?? 0)!]: true,
                    [stylesApp.invisible]: chain() === null,
                  }}
                  style={cartButtonStyle()}
                  value={props.scoreBoardPrice[chain() ?? 0] * 100}
                  onClick={() => {
                    const newCart = [...cart()];
                    newCart[i] = null;
                    updateValues(newCart);
                  }}
                />
              </>
            )}
          </Index>
        </fieldset>{' '}
        <label>
          <input
            ref={endGameCheckbox}
            type="checkbox"
            checked={endGame()}
            onInput={(e) => setEndGame(e.currentTarget.checked)}
          />{' '}
          End game
        </label>{' '}
        <input ref={okButton} type="button" value="OK" onClick={handleOK} />
      </div>
    </div>
  );
}

const enum AvailableButtonStatus {
  Enabled,
  Disabled,
  Invisible,
}

// src/lib/PurchaseShares.svelte
<svelte:options immutable />

<script lang="ts" context="module">
	enum AvailableButtonStatus {
		Enabled,
		Disabled,
		Invisible,
	}
</script>

<script lang="ts">
	import type { PB_GameBoardType } from '../common/pb';
	import {
		KEY_SHIFT,
		allChains,
		gameBoardTypeToCSSClassName,
		gameBoardTypeToHotelInitial,
		keyboardEventCodeToGameBoardType,
		keyboardEventToKeysAlsoPressed,
	} from './helpers';

	export let scoreBoardAvailable: number[];
	export let scoreBoardPrice: number[];
	export let cash: number;
	export let buttonSize: number;
	export let keyboardShortcutsEnabled: boolean;
	export let onSharesPurchased: (chains: PB_GameBoardType[], endGame: boolean) => void;

	let availableButtonStatuses: AvailableButtonStatus[];
	let costTotal = 0;
	let costLeft = 0;
	let cart: (number | null)[] = [null, null, null];
	let endGame = false;

	$: {
		const chainToNumSharesInCart = new Map<number, number>();
		costTotal = 0;
		let numItemsInCart = 0;
		for (let i = 0; i < cart.length; i++) {
			const chain = cart[i];
			if (chain !== null) {
				chainToNumSharesInCart.set(chain, (chainToNumSharesInCart.get(chain) ?? 0) + 1);
				costTotal += scoreBoardPrice[chain];
				numItemsInCart++;
			}
		}
		costLeft = cash - costTotal;

		availableButtonStatuses = allChains.map((chain) => {
			const numAvailable = scoreBoardAvailable[chain];
			const price = scoreBoardPrice[chain];

			if (price > 0 && numAvailable > 0) {
				const numRemaining = numAvailable - (chainToNumSharesInCart.get(chain) ?? 0);
				const canAddThis = numItemsInCart < 3 && numRemaining > 0 && price <= costLeft;

				return canAddThis ? AvailableButtonStatus.Enabled : AvailableButtonStatus.Disabled;
			} else {
				return AvailableButtonStatus.Invisible;
			}
		});
	}

	const availableButtons: (HTMLInputElement | null)[] = new Array(allChains.length);
	availableButtons.fill(null);
	let endGameCheckbox: HTMLInputElement | null = null;
	let okButton: HTMLInputElement | null = null;

	$: buttonStyle = `width: ${buttonSize}px; height: ${buttonSize}px`;
	$: cartButtonStyle = `width: ${Math.floor(buttonSize * (4 / 3))}px; height: ${buttonSize}px`;

	function handleKeydown(event: KeyboardEvent) {
		if (keyboardShortcutsEnabled) {
			const keysAlsoPressed = keyboardEventToKeysAlsoPressed(event);
			const gameBoardType = keyboardEventCodeToGameBoardType.get(event.code);

			if (keysAlsoPressed === 0) {
				if (gameBoardType !== undefined) {
					const button = availableButtons[gameBoardType];
					if (button) {
						button.focus();
						button.click();
					}

					event.preventDefault();
				} else if (
					event.code === 'Backspace' ||
					event.code === 'Delete' ||
					event.code === 'NumpadSubtract'
				) {
					for (let i = cart.length - 1; i >= 0; i--) {
						if (cart[i] !== null) {
							cart = [...cart];
							cart[i] = null;
							break;
						}
					}

					event.preventDefault();
				} else if (event.code === 'KeyE' || event.code === 'NumpadMultiply') {
					endGameCheckbox?.focus();
					endGameCheckbox?.click();

					event.preventDefault();
				} else if (
					event.code === 'KeyO' ||
					event.code === 'Digit0' ||
					event.code === 'Numpad0' ||
					event.code === 'Digit8' ||
					event.code === 'Numpad8'
				) {
					okButton?.focus();

					event.preventDefault();
				}
			} else if (keysAlsoPressed === KEY_SHIFT) {
				if (gameBoardType !== undefined) {
					for (let i = cart.length - 1; i >= 0; i--) {
						if (cart[i] === gameBoardType) {
							cart = [...cart];
							cart[i] = null;
							break;
						}
					}

					event.preventDefault();
				}
			}
		}
	}

	function handleOK() {
		const chains: PB_GameBoardType[] = [];
		for (let i = 0; i < cart.length; i++) {
			const entry = cart[i];
			if (entry !== null) {
				chains.push(entry);
			}
		}

		onSharesPurchased(chains, endGame);
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<div style="font-size: {Math.floor(buttonSize * 0.4)}px">
	<div class="topRow">
		<fieldset>
			<legend>Available</legend>
			{#each availableButtonStatuses as availableButtonStatus, chain}
				<input
					type="button"
					class="hotelButton {gameBoardTypeToCSSClassName.get(chain)}"
					class:invisible={availableButtonStatus === AvailableButtonStatus.Invisible}
					disabled={availableButtonStatus !== AvailableButtonStatus.Enabled}
					style={buttonStyle}
					value={gameBoardTypeToHotelInitial.get(chain)}
					bind:this={availableButtons[chain]}
					on:click={() => {
						for (let i = 0; i < cart.length; i++) {
							if (cart[i] === null) {
								cart = [...cart];
								cart[i] = chain;
								break;
							}
						}
					}}
				/>
				{' '}
			{/each}
		</fieldset>
		<fieldset>
			<legend>Cost</legend>
			<table>
				<tbody>
					<tr>
						<td>Total</td>
						<td>{costTotal * 100}</td>
					</tr>
					<tr>
						<td>Left</td>
						<td>{costLeft * 100}</td>
					</tr>
				</tbody>
			</table>
		</fieldset>
	</div>
	<div>
		<fieldset>
			<legend>Cart</legend>
			{#each cart as chain, i}
				<input
					type="button"
					class="hotelButton {gameBoardTypeToCSSClassName.get(chain ?? 0)}"
					class:invisible={chain === null}
					style={cartButtonStyle}
					value={scoreBoardPrice[chain ?? 0] * 100}
					on:click={() => {
						cart = [...cart];
						cart[i] = null;
					}}
				/>
				{' '}
			{/each}
		</fieldset>
		<label>
			<input type="checkbox" bind:checked={endGame} bind:this={endGameCheckbox} />
			End game
		</label>
		<input type="button" value="OK" bind:this={okButton} on:click={handleOK} />
	</div>
</div>

<style>
	fieldset {
		display: inline-block;
		margin: 0;
		padding: 0 3px 3px;
	}

	legend {
		padding: 0 5px;
	}

	input:disabled {
		background-color: #d3d3d3;
		color: #555555;
	}

	label {
		margin-right: 4px;
	}

	.topRow fieldset {
		vertical-align: top;
	}

	table {
		border-collapse: collapse;
		border-spacing: 0;
	}

	td:nth-child(1) {
		text-align: left;
	}

	td:nth-child(2) {
		text-align: right;
		width: 4em;
	}
</style>
