// src/client/components/ScoreBoard.tsx
import { createMemo, For, Index, Match, Switch } from 'solid-js';
import { ScoreBoardIndexEnum } from '../../common/enums';
import { gameModeToNumPlayers, gameModeToTeamSize } from '../../common/helpers';
import { PB_GameMode } from '../../common/pb';
import {
  allChains,
  gameBoardTypeToCSSClassName,
  gameBoardTypeToHotelInitial,
  teamNumberToCSSClassName,
} from '../helpers';
import styles from './ScoreBoard.module.css';

export function ScoreBoard(props: {
  usernames: string[];
  scoreBoard: number[][];
  scoreBoardAvailable: number[];
  scoreBoardChainSize: number[];
  scoreBoardPrice: number[];
  safeChains: boolean[];
  turnPlayerID: number;
  movePlayerID: number;
  gameMode: PB_GameMode;
  cellWidth: number;
}) {
  const isTeamGame = createMemo(() => gameModeToTeamSize.get(props.gameMode)! > 1);

  const numTeams = createMemo(() =>
    isTeamGame()
      ? gameModeToNumPlayers.get(props.gameMode)! / gameModeToTeamSize.get(props.gameMode)!
      : 0,
  );

  const teamNumbers = createMemo(() => numTeamsToTeamNumbers[numTeams()]);

  const teamTotals = createMemo(() => {
    if (isTeamGame()) {
      const totals: (number | undefined)[] = [0, 0, 0];
      const sb = props.scoreBoard;
      const nt = numTeams();

      for (let playerID = 0; playerID < sb.length; playerID++) {
        totals[playerID % nt]! += sb[playerID][ScoreBoardIndexEnum.Net];
      }

      if (nt === 2) {
        totals[2] = totals[1];
        totals[1] = totals[0];
        totals[0] = undefined;
      }

      return totals;
    } else {
      return defaultTeamTotals;
    }
  });

  return (
    <table
      class={styles.root}
      style={{
        'font-size': `${Math.floor(props.cellWidth * 0.6)}px`,
        width: `${props.cellWidth * 18 + 2}px`,
      }}
    >
      <tbody>
        <tr>
          <td class={styles.playerHeader}>Player</td>
          <For each={allChains}>
            {(chain) => (
              <td class={gameBoardTypeToCSSClassName.get(chain)}>
                {gameBoardTypeToHotelInitial.get(chain)}
              </td>
            )}
          </For>
          <td class={styles.cashAndNetHeader}>Cash</td>
          <td class={styles.cashAndNetHeader}>Net</td>
        </tr>

        <Index each={props.usernames}>
          {(username, playerID) => (
            <ScoreBoardRow
              isPlayerRow={true}
              title={username()}
              isPlayersTurn={playerID === props.turnPlayerID}
              isPlayersMove={playerID === props.movePlayerID}
              scoreBoardRow={props.scoreBoard[playerID]}
              safeChains={props.safeChains}
              defaultClassName={
                isTeamGame()
                  ? teamNumberToCSSClassName.get((playerID % numTeams()) + 1)!
                  : styles.player
              }
              zeroValueReplacement=""
              teamNumber={undefined}
              teamTotal={undefined}
            />
          )}
        </Index>

        <ScoreBoardRow
          isPlayerRow={false}
          title="Available"
          isPlayersTurn={false}
          isPlayersMove={false}
          scoreBoardRow={props.scoreBoardAvailable}
          safeChains={props.safeChains}
          defaultClassName={styles.availableChainSizeAndPrice}
          zeroValueReplacement="0"
          teamNumber={teamNumbers()[0]}
          teamTotal={teamTotals()[0]}
        />
        <ScoreBoardRow
          isPlayerRow={false}
          title="Chain Size"
          isPlayersTurn={false}
          isPlayersMove={false}
          scoreBoardRow={props.scoreBoardChainSize}
          safeChains={props.safeChains}
          defaultClassName={styles.availableChainSizeAndPrice}
          zeroValueReplacement="-"
          teamNumber={teamNumbers()[1]}
          teamTotal={teamTotals()[1]}
        />
        <ScoreBoardRow
          isPlayerRow={false}
          title="Price ($00)"
          isPlayersTurn={false}
          isPlayersMove={false}
          scoreBoardRow={props.scoreBoardPrice}
          safeChains={props.safeChains}
          defaultClassName={styles.availableChainSizeAndPrice}
          zeroValueReplacement="-"
          teamNumber={teamNumbers()[2]}
          teamTotal={teamTotals()[2]}
        />
      </tbody>
    </table>
  );
}

function ScoreBoardRow(props: {
  isPlayerRow: boolean;
  title: string;
  isPlayersTurn: boolean;
  isPlayersMove: boolean;
  scoreBoardRow: number[];
  safeChains: boolean[];
  defaultClassName: string;
  zeroValueReplacement: string;
  teamNumber: number | undefined;
  teamTotal: number | undefined;
}) {
  return (
    <tr class={props.defaultClassName}>
      <td
        class={
          props.isPlayersTurn
            ? styles.isPlayersTurn
            : props.isPlayersMove
              ? styles.isPlayersMove
              : props.isPlayerRow
                ? styles.player
                : undefined
        }
        title={props.isPlayerRow ? props.title : undefined}
      >
        {props.title}
      </td>

      <Index each={props.safeChains}>
        {(isSafe, chain) => (
          <td classList={{ [styles.safeChain]: isSafe() }}>
            {props.scoreBoardRow[chain] === 0
              ? props.zeroValueReplacement
              : props.scoreBoardRow[chain]}
          </td>
        )}
      </Index>

      <Switch>
        <Match when={props.isPlayerRow}>
          <td>{props.scoreBoardRow[ScoreBoardIndexEnum.Cash] * 100}</td>
          <td>{props.scoreBoardRow[ScoreBoardIndexEnum.Net] * 100}</td>
        </Match>
        <Match when={true}>
          <td class={styles.notTeamScore}>
            {props.teamNumber !== undefined ? `Team ${props.teamNumber}` : ''}
          </td>
          <td
            classList={{
              [props.teamNumber !== undefined
                ? teamNumberToCSSClassName.get(props.teamNumber)!
                : '']: true,
              [styles.teamScore]: props.teamNumber !== undefined,
              [styles.notTeamScore]: props.teamNumber === undefined,
            }}
          >
            {props.teamTotal !== undefined ? props.teamTotal * 100 : ''}
          </td>
        </Match>
      </Switch>
    </tr>
  );
}

const numTeamsToTeamNumbers = [[undefined, undefined, undefined], [], [undefined, 1, 2], [1, 2, 3]];

const defaultTeamTotals = [undefined, undefined, undefined];

// src/lib/ScoreBoard.svelte
<svelte:options immutable />

<script lang="ts">
  import { ScoreBoardIndexEnum } from '../common/enums';
  import type { PB_GameMode } from '../common/pb';
  import {
    allChains,
    gameBoardTypeToCSSClassName,
    gameBoardTypeToHotelInitial,
    gameModeToNumPlayers,
    gameModeToTeamSize,
    teamNumberToCSSClassName,
  } from './helpers';
  import ScoreBoardRow from './ScoreBoardRow.svelte';

  export let usernames: string[];
  export let scoreBoard: number[][];
  export let scoreBoardAvailable: number[];
  export let scoreBoardChainSize: number[];
  export let scoreBoardPrice: number[];
  export let safeChains: boolean[];
  export let turnPlayerID: number;
  export let movePlayerID: number;
  export let gameMode: PB_GameMode;
  export let cellWidth: number;

  const isTeamGame = gameModeToTeamSize.get(gameMode)! > 1;
  const numTeams = gameModeToNumPlayers.get(gameMode)! / gameModeToTeamSize.get(gameMode)!;

  const teamNumbers: (number | undefined)[] = new Array(3);
  const teamTotals: (number | undefined)[] = new Array(3);
  if (isTeamGame) {
    if (numTeams === 2) {
      teamNumbers[1] = 1;
      teamNumbers[2] = 2;
      teamTotals[1] = getTeamTotal(scoreBoard, numTeams, 1);
      teamTotals[2] = getTeamTotal(scoreBoard, numTeams, 2);
    } else {
      teamNumbers[0] = 1;
      teamNumbers[1] = 2;
      teamNumbers[2] = 3;
      teamTotals[0] = getTeamTotal(scoreBoard, numTeams, 1);
      teamTotals[1] = getTeamTotal(scoreBoard, numTeams, 2);
      teamTotals[2] = getTeamTotal(scoreBoard, numTeams, 3);
    }
  }

  const defaultClassNames: string[] = new Array(usernames.length);
  for (let playerID = 0; playerID < usernames.length; playerID++) {
    defaultClassNames[playerID] = isTeamGame ? teamNumberToCSSClassName.get((playerID % numTeams) + 1)! : 'player';
  }

  function getTeamTotal(scoreBoard: number[][], numTeams: number, teamNumber: number) {
    let teamTotal = 0;
    for (let playerID = teamNumber - 1; playerID < scoreBoard.length; playerID += numTeams) {
      teamTotal += scoreBoard[playerID][ScoreBoardIndexEnum.Net];
    }
    return teamTotal;
  }
</script>

<table style="font-size: {Math.floor(cellWidth * 0.6)}px; width: {cellWidth * 18 + 2}px;">
  <tbody>
    <tr>
      <td class="playerHeader">Player</td>
      {#each allChains as chain}
        <td class={gameBoardTypeToCSSClassName.get(chain)}>{gameBoardTypeToHotelInitial.get(chain)}</td>
      {/each}
      <td class="cashAndNetHeader">Cash</td>
      <td class="cashAndNetHeader">Net</td>
    </tr>

    {#each usernames as username, playerID}
      <ScoreBoardRow
        isPlayerRow={true}
        title={username}
        isPlayersTurn={playerID === turnPlayerID}
        isPlayersMove={playerID === movePlayerID}
        scoreBoardRow={scoreBoard[playerID]}
        {safeChains}
        defaultClassName={defaultClassNames[playerID]}
        zeroValueReplacement=""
      />
    {/each}

    <ScoreBoardRow
      isPlayerRow={false}
      title="Available"
      isPlayersTurn={false}
      isPlayersMove={false}
      scoreBoardRow={scoreBoardAvailable}
      {safeChains}
      defaultClassName="availableChainSizeAndPrice"
      zeroValueReplacement="0"
      teamNumber={teamNumbers[0]}
      teamTotal={teamTotals[0]}
    />
    <ScoreBoardRow
      isPlayerRow={false}
      title="Chain Size"
      isPlayersTurn={false}
      isPlayersMove={false}
      scoreBoardRow={scoreBoardChainSize}
      {safeChains}
      defaultClassName="availableChainSizeAndPrice"
      zeroValueReplacement="-"
      teamNumber={teamNumbers[1]}
      teamTotal={teamTotals[1]}
    />
    <ScoreBoardRow
      isPlayerRow={false}
      title="Price ($00)"
      isPlayersTurn={false}
      isPlayersMove={false}
      scoreBoardRow={scoreBoardPrice}
      {safeChains}
      defaultClassName="availableChainSizeAndPrice"
      zeroValueReplacement="-"
      teamNumber={teamNumbers[2]}
      teamTotal={teamTotals[2]}
    />
  </tbody>
</table>

<style>
  table {
    background-color: #ffffff;
    border-collapse: collapse;
    font-weight: bold;
    table-layout: fixed;
  }

  table :global(td) {
    border: 2px solid #f6f4f2;
    overflow: hidden;
    white-space: nowrap;
  }

  table :global(td:nth-child(1)) {
    padding-left: 3px;
    text-align: left;
    width: calc(100% * 5 / 18);
  }

  table :global(td:nth-child(n + 2):nth-child(-n + 8)) {
    text-align: center;
    width: calc(100% / 18);
  }

  table :global(td:nth-child(n + 9)) {
    padding-right: 3px;
    text-align: right;
    width: calc(100% * 3 / 18);
  }

  .playerHeader {
    background-color: #c0c0ff;
  }

  .cashAndNetHeader {
    background-color: #008000;
    color: #ffffff;
  }

  table :global(.player) {
    background-color: #ffffff;
  }

  table :global(.availableChainSizeAndPrice) {
    background-color: #c0ffff;
  }
</style>
