// src/client/components/TileRackReadOnly.tsx
import { createMemo, Index, type JSX } from 'solid-js';
import { toTileString } from '../../common/helpers.js';
import { type PB_GameBoardType } from '../../common/pb.js';
import stylesApp from '../App.module.css';
import { gameBoardTypeToCSSClassName } from '../styleHelpers.js';
import { allTileDataFromTilesAndTypes } from './TileRack.jsx';
import styles from './TileRackReadOnly.module.css';

export function TileRackReadOnly(props: {
  tiles: (number | null)[];
  types: (PB_GameBoardType | null)[];
  buttonSize: number;
}) {
  const allTileData = allTileDataFromTilesAndTypes(
    // eslint-disable-next-line solid/reactivity
    () => props.tiles,
    // eslint-disable-next-line solid/reactivity
    () => props.types,
  );

  const buttonStyle = createMemo<JSX.CSSProperties>(() => ({
    width: `${props.buttonSize}px`,
    height: `${props.buttonSize}px`,
  }));

  return (
    <div class={styles.root} style={{ 'font-size': `${Math.floor(props.buttonSize * 0.4)}px` }}>
      <Index each={allTileData}>
        {(tileData) => (
          <div
            classList={{
              [styles.button]: true,
              [tileData().type !== null ? gameBoardTypeToCSSClassName.get(tileData().type!)! : '']:
                tileData().type !== null,
              [stylesApp.invisible]: tileData().type === null,
            }}
            style={buttonStyle()}
          >
            <div>{tileData().tile !== null ? toTileString(tileData().tile!) : '?'}</div>
          </div>
        )}
      </Index>
    </div>
  );
}

// src/lib/TileRackReadOnly.svelte
<script lang="ts">
  import { toTileString } from '../common/helpers';
  import type { PB_GameBoardType } from '../common/pb';
  import { gameBoardTypeToCSSClassName } from './helpers';

  export let tiles: (number | null)[];
  export let types: (PB_GameBoardType | null)[];
  export let buttonSize: number;

  const allTileData: ({ tile: number; type: PB_GameBoardType } | undefined)[] = new Array(6);
  allTileData.fill(undefined);

  $: for (let i = 0; i < tiles.length; i++) {
    const tile = tiles[i];
    const type = types[i];

    if (tile !== null && type !== null) {
      if (allTileData[i]) {
        allTileData[i]!.tile = tile;
        allTileData[i]!.type = type;
      } else {
        allTileData[i] = { tile, type };
      }
    } else {
      allTileData[i] = undefined;
    }
  }

  $: buttonStyle = `width: ${buttonSize}px; height: ${buttonSize}px`;
</script>

<div class="root" style="font-size: {Math.floor(buttonSize * 0.4)}px">
  {#each allTileData as tileData}
    {#if tileData}
      <div class="button {gameBoardTypeToCSSClassName.get(tileData.type)}" style={buttonStyle}>
        <div>{toTileString(tileData.tile)}</div>
      </div>
    {:else}
      <div class="button invisible" style={buttonStyle}>?</div>
    {/if}
  {/each}
</div>

<style>
  .root :not(:last-child) {
    margin-right: 4px;
  }

  .button {
    display: inline-block;
    font-weight: bold;
    text-align: center;
  }

  .button > div {
    position: relative;
    top: 50%;
    transform: translateY(-50%);
  }
</style>
