// src/client/components/TileRack.tsx
import { type Accessor, createEffect, createMemo, Index, type JSX, onMount } from 'solid-js';
import { createStore } from 'solid-js/store';
import { toTileString } from '../../common/helpers.js';
import { PB_GameBoardType } from '../../common/pb.js';
import * as stylesApp from '../App.module.css';
import { type ProcessMyKeyboardEventRef } from '../myKeyboardEvents.js';
import { gameBoardTypeToCSSClassName } from '../styleHelpers.js';
import * as styles from './TileRack.module.css';

export function TileRack(props: {
  ref: (ref: ProcessMyKeyboardEventRef) => void;
  tiles: (number | null)[];
  types: (PB_GameBoardType | null)[];
  buttonSize: number;
  onTileClicked: (tile: number) => void;
}) {
  const allTileData = allTileDataFromTilesAndTypes(
    // eslint-disable-next-line solid/reactivity
    () => props.tiles,
    // eslint-disable-next-line solid/reactivity
    () => props.types,
  );

  const buttonStyle = createMemo<JSX.CSSProperties>(() => ({
    width: `${props.buttonSize}px`,
    height: `${props.buttonSize}px`,
  }));

  const inputs: HTMLInputElement[] = new Array(6);
  onMount(() => {
    props.ref({
      processMyKeyboardEvent: (myKeyboardEvent) => {
        const tileIndex = keyboardEventCodeToTileIndex.get(myKeyboardEvent.code);

        if (tileIndex !== undefined && myKeyboardEvent.modifiers === 0) {
          inputs[tileIndex].focus();
        }
      },
    });
  });

  return (
    <div class={styles.root} style={{ 'font-size': `${Math.floor(props.buttonSize * 0.4)}px` }}>
      <Index each={allTileData}>
        {(tileData, index) => (
          <input
            ref={inputs[index]}
            type="button"
            classList={{
              [stylesApp.hotelButton]: true,
              [tileData().type !== null ? gameBoardTypeToCSSClassName.get(tileData().type!)! : '']:
                tileData().type !== null,
              [stylesApp.invisible]: tileData().type === null,
            }}
            style={buttonStyle()}
            value={tileData().tile !== null ? toTileString(tileData().tile!) : '?'}
            disabled={
              tileData().type === PB_GameBoardType.CANT_PLAY_EVER ||
              tileData().type === PB_GameBoardType.CANT_PLAY_NOW
            }
            onClick={() => props.onTileClicked(tileData().tile!)}
          />
        )}
      </Index>
    </div>
  );
}

export function allTileDataFromTilesAndTypes(
  tiles: Accessor<(number | null)[]>,
  types: Accessor<(PB_GameBoardType | null)[]>,
) {
  const [allTileData, setAllTileData] = createStore<
    { tile: number | null; type: PB_GameBoardType | null }[]
  >([
    { tile: null, type: null },
    { tile: null, type: null },
    { tile: null, type: null },
    { tile: null, type: null },
    { tile: null, type: null },
    { tile: null, type: null },
  ]);

  createEffect(() => {
    const t = tiles();
    for (let i = 0; i < t.length; i++) {
      setAllTileData(i, 'tile', t[i]);
    }
  });

  createEffect(() => {
    const t = types();
    for (let i = 0; i < t.length; i++) {
      setAllTileData(i, 'type', t[i]);
    }
  });

  return allTileData;
}

export const keyboardEventCodeToTileIndex = new Map([
  ['Digit1', 0],
  ['Numpad1', 0],
  ['Digit2', 1],
  ['Numpad2', 1],
  ['Digit3', 2],
  ['Numpad3', 2],
  ['Digit4', 3],
  ['Numpad4', 3],
  ['Digit5', 4],
  ['Numpad5', 4],
  ['Digit6', 5],
  ['Numpad6', 5],
]);

// src/lib/TileRack.svelte
<script lang="ts" context="module">
  type TileData = {
    tile: number;
    type: PB_GameBoardType;
  };

  export const keyboardEventCodeToTileIndex = new Map([
    ['Digit1', 0],
    ['Numpad1', 0],
    ['Digit2', 1],
    ['Numpad2', 1],
    ['Digit3', 2],
    ['Numpad3', 2],
    ['Digit4', 3],
    ['Numpad4', 3],
    ['Digit5', 4],
    ['Numpad5', 4],
    ['Digit6', 5],
    ['Numpad6', 5],
  ]);
</script>

<script lang="ts">
  import { toTileString } from '../common/helpers';
  import { PB_GameBoardType } from '../common/pb';
  import { gameBoardTypeToCSSClassName, keyboardEventToKeysAlsoPressed } from './helpers';

  export let tiles: (number | null)[];
  export let types: (PB_GameBoardType | null)[];
  export let buttonSize: number;
  export let keyboardShortcutsEnabled: boolean;
  export let onTileClicked: (tile: number) => void;

  const allTileData: (TileData | undefined)[] = new Array(6);
  allTileData.fill(undefined);

  const inputs: (HTMLInputElement | null)[] = new Array(6);
  inputs.fill(null);

  $: for (let i = 0; i < tiles.length; i++) {
    const tile = tiles[i];
    const type = types[i];

    if (tile !== null && type !== null) {
      if (allTileData[i]) {
        allTileData[i]!.tile = tile;
        allTileData[i]!.type = type;
      } else {
        allTileData[i] = { tile, type };
      }
    } else {
      allTileData[i] = undefined;
    }
  }

  $: buttonStyle = `width: ${buttonSize}px; height: ${buttonSize}px`;

  function handleKeydown(event: KeyboardEvent) {
    if (keyboardShortcutsEnabled) {
      const tileIndex = keyboardEventCodeToTileIndex.get(event.code);

      if (tileIndex !== undefined && keyboardEventToKeysAlsoPressed(event) === 0) {
        inputs[tileIndex]?.focus();

        event.preventDefault();
      }
    }
  }

  function onClick(tileData: TileData | undefined) {
    if (tileData) {
      onTileClicked(tileData.tile);
    }
  }
</script>

<svelte:window on:keydown={handleKeydown} />

<div class="root" style="font-size: {Math.floor(buttonSize * 0.4)}px">
  {#each allTileData as tileData, tileIndex}
    {#if tileData}
      <input
        type="button"
        class="hotelButton {gameBoardTypeToCSSClassName.get(tileData.type)}"
        style={buttonStyle}
        value={toTileString(tileData.tile)}
        disabled={tileData.type === PB_GameBoardType.CANT_PLAY_EVER ||
          tileData.type === PB_GameBoardType.CANT_PLAY_NOW}
        on:click={() => onClick(tileData)}
        bind:this={inputs[tileIndex]}
      />
    {:else}
      <input type="button" class="invisible" style={buttonStyle} value="?" />
    {/if}
  {/each}
</div>

<style>
  .root :not(:last-child) {
    margin-right: 4px;
  }
</style>
