// src/lib/CreateGame.svelte
<svelte:options immutable />

<script lang="ts">
	import type { PB_GameMode } from '../common/pb';
	import { allGameModes, gameModeToString } from './helpers';

	export let gameMode: PB_GameMode;
	export let onSubmit: (gameMode: PB_GameMode) => void;
</script>

<div>
	Mode:
	<select bind:value={gameMode}>
		{#each allGameModes as gameMode}
			<option value={gameMode}>
				{gameModeToString.get(gameMode)}
			</option>
		{/each}
	</select>
	<input type="button" value="Create Game" on:click={() => onSubmit(gameMode)} />
</div>

// src/client/components/CreateGame.tsx
import { createSignal, For } from 'solid-js';
import { type PB_GameMode } from '../../common/pb.js';
import { allGameModes, gameModeToString } from '../helpers.js';

export function CreateGame(props: {
  initialGameMode: PB_GameMode;
  onSubmit: (gameMode: PB_GameMode) => void;
}) {
  const [selectedGameMode, setSelectedGameMode] = createSignal(props.initialGameMode);

  return (
    <div>
      Game mode:{' '}
      <select
        value={selectedGameMode()}
        onInput={(e) => setSelectedGameMode(parseInt(e.currentTarget.value, 10))}
      >
        <For each={allGameModes}>
          {(gameMode) => <option value={gameMode}>{gameModeToString.get(gameMode)}</option>}
        </For>
      </select>{' '}
      <input type="button" value="Create Game" onClick={() => props.onSubmit(selectedGameMode())} />
    </div>
  );
}
