// src/lib/GameListing.svelte
<svelte:options immutable />

<script lang="ts">
	import { gameModeToNumPlayers, gameModeToTeamSize } from '../common/helpers';
	import type { PB_GameBoardType, PB_GameMode, PB_GameStatus } from '../common/pb';
	import { gameModeToString, gameStatusToString, teamNumberToCSSClassName } from './helpers';
	import MiniGameBoard from './MiniGameBoard.svelte';

	export let gameBoard: PB_GameBoardType[][];
	export let usernames: (string | null)[];
	export let gameDisplayNumber: number;
	export let gameMode: PB_GameMode;
	export let gameStatus: PB_GameStatus;
	export let onEnterClicked: () => void;

	$: isTeamGame = gameModeToTeamSize.get(gameMode)! > 1;
	$: numTeams = gameModeToNumPlayers.get(gameMode)! / gameModeToTeamSize.get(gameMode)!;
</script>

<div>
	<div class="miniGameBoardWrapper">
		<MiniGameBoard {gameBoard} cellSize={15} />
	</div>
	<table>
		<tbody>
			{#each usernames as username, playerID}
				<tr>
					<td
						class={isTeamGame ? teamNumberToCSSClassName.get((playerID % numTeams) + 1) : 'player'}
						>{username !== null ? username : ''}</td
					>
				</tr>
			{/each}
		</tbody>
	</table>
	<div class="other">
		<div>Game #{gameDisplayNumber}</div>
		<div>{gameModeToString.get(gameMode)}</div>
		<div>{gameStatusToString.get(gameStatus)}</div>
		<div>
			<input type="button" value="Enter" on:click={onEnterClicked} />
		</div>
	</div>
</div>

<style>
	.miniGameBoardWrapper {
		display: inline-block;
	}

	table {
		border-collapse: collapse;
		display: inline-block;
		font-weight: bold;
		vertical-align: top;
	}

	td {
		border: 2px solid #f6f4f2;
		height: 22px;
		max-width: 200px;
		overflow: hidden;
		padding-left: 3px;
		text-align: left;
		white-space: nowrap;
		width: 200px;
	}

	.other {
		display: inline-block;
		font-weight: bold;
		vertical-align: top;
	}

	.player {
		background-color: #ffffff;
	}
</style>

// src/client/components/GameListing.tsx
import React from 'react';
import { gameModeToNumPlayers, gameModeToTeamSize } from '../../common/helpers';
import type { PB_GameBoardType, PB_GameMode, PB_GameStatus } from '../../common/pb';
import { gameModeToString, gameStatusToString, teamNumberToCSSClassName } from '../helpers';
import * as style from './GameListing.scss';
import { MiniGameBoard } from './MiniGameBoard';

export interface GameListingProps {
  gameBoard: PB_GameBoardType[][];
  usernames: (string | null)[];
  gameDisplayNumber: number;
  gameMode: PB_GameMode;
  gameStatus: PB_GameStatus;
  onEnterClicked: () => void;
}

export const GameListing = React.memo(function GameListing({
  gameBoard,
  usernames,
  gameDisplayNumber,
  gameMode,
  gameStatus,
  onEnterClicked,
}: GameListingProps) {
  const isTeamGame = gameModeToTeamSize.get(gameMode)! > 1;
  const numTeams = gameModeToNumPlayers.get(gameMode)! / gameModeToTeamSize.get(gameMode)!;

  return (
    <div>
      <div className={style.miniGameBoardWrapper}>
        <MiniGameBoard gameBoard={gameBoard} cellSize={15} />
      </div>
      <table className={style.players}>
        <tbody>
          {usernames.map((username, i) => (
            <tr key={i}>
              <td className={isTeamGame ? teamNumberToCSSClassName.get((i % numTeams) + 1) : style.player}>{username}</td>
            </tr>
          ))}
        </tbody>
      </table>
      <div className={style.other}>
        <div>Game #{gameDisplayNumber}</div>
        <div>{gameModeToString.get(gameMode)}</div>
        <div>{gameStatusToString.get(gameStatus)}</div>
        <div>
          <input type={'button'} value={'Enter'} onClick={onEnterClicked} />
        </div>
      </div>
    </div>
  );
});
