// src/lib/HotelName.svelte
<svelte:options immutable />

<script lang="ts">
	import type { PB_GameBoardType } from '../common/pb';
	import { gameBoardTypeToCSSClassName, gameBoardTypeToHotelName } from './helpers';

	export let chain: PB_GameBoardType;
</script>

<span class={gameBoardTypeToCSSClassName.get(chain)}>{gameBoardTypeToHotelName.get(chain)}</span>

// src/client/components/HotelName.tsx
import { type PB_GameBoardType } from '../../common/pb.js';
import { gameBoardTypeToHotelName } from '../helpers.js';
import { gameBoardTypeToCSSClassName } from '../styleHelpers.js';
import * as styles from './HotelName.module.css';

export function HotelName(props: { chain: PB_GameBoardType }) {
  return (
    <span
      classList={{
        [styles.root]: true,
        [gameBoardTypeToCSSClassName.get(props.chain)!]: true,
      }}
    >
      {gameBoardTypeToHotelName.get(props.chain)}
    </span>
  );
}
