// src/lib/NextGameAction.svelte
<svelte:options immutable />

<script lang="ts">
	import type { ActionBase } from '../common/gameActions/base';
	import { ActionDisposeOfShares } from '../common/gameActions/disposeOfShares';
	import { ActionGameOver } from '../common/gameActions/gameOver';
	import { ActionPlayTile } from '../common/gameActions/playTile';
	import { ActionPurchaseShares } from '../common/gameActions/purchaseShares';
	import { ActionSelectChainToDisposeOfNext } from '../common/gameActions/selectChainToDisposeOfNext';
	import { ActionSelectMergerSurvivor } from '../common/gameActions/selectMergerSurvivor';
	import { ActionSelectNewChain } from '../common/gameActions/selectNewChain';
	import { ActionStartGame } from '../common/gameActions/startGame';
	import NextGameActionHotelInitialsList from './children/NextGameActionHotelInitialsList.svelte';
	import HotelName from './HotelName.svelte';
	import Username from './Username.svelte';

	export let action: ActionBase;
</script>

{#if action instanceof ActionStartGame}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to start the game.
	</div>
{:else if action instanceof ActionPlayTile}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to play a tile.
	</div>
{:else if action instanceof ActionSelectNewChain}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to select new chain (<NextGameActionHotelInitialsList
			chains={action.availableChains}
		/>).
	</div>
{:else if action instanceof ActionSelectMergerSurvivor}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to select merger survivor
		(<NextGameActionHotelInitialsList chains={action.chainsBySize[0]} />).
	</div>
{:else if action instanceof ActionSelectChainToDisposeOfNext}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to select chain to dispose
		of next (<NextGameActionHotelInitialsList chains={action.defunctChains} />).
	</div>
{:else if action instanceof ActionDisposeOfShares}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to dispose of <HotelName
			chain={action.defunctChain}
		/> shares.
	</div>
{:else if action instanceof ActionPurchaseShares}
	<div>
		Waiting for <Username username={action.game.usernames[action.playerID]} /> to purchase shares.
	</div>
{:else if action instanceof ActionGameOver}
	<div>Game over.</div>
{:else}
	<div>Unknown game status.</div>
{/if}

<style>
	div {
		font-weight: bold;
		overflow: hidden;
		white-space: nowrap;
	}
</style>

// src/client/components/NextGameAction.tsx
import { Match, Switch } from 'solid-js';
import { ActionBase } from '../../common/gameActions/base';
import { ActionDisposeOfShares } from '../../common/gameActions/disposeOfShares';
import { ActionGameOver } from '../../common/gameActions/gameOver';
import { ActionPlayTile } from '../../common/gameActions/playTile';
import { ActionPurchaseShares } from '../../common/gameActions/purchaseShares';
import { ActionSelectChainToDisposeOfNext } from '../../common/gameActions/selectChainToDisposeOfNext';
import { ActionSelectMergerSurvivor } from '../../common/gameActions/selectMergerSurvivor';
import { ActionSelectNewChain } from '../../common/gameActions/selectNewChain';
import { ActionStartGame } from '../../common/gameActions/startGame';
import { HotelName } from './HotelName';
import styles from './NextGameAction.module.css';
import { NextGameActionHotelInitialsList } from './NextGameActionHotelInitialsList';
import { Username } from './Username';

export function NextGameAction(props: { action: ActionBase }) {
  return (
    <div class={styles.root}>
      <Switch fallback={<>Unknown game status.</>}>
        <Match when={props.action instanceof ActionStartGame}>
          <NextGameActionStartGame action={props.action as ActionStartGame} />
        </Match>
        <Match when={props.action instanceof ActionPlayTile}>
          <NextGameActionPlayTile action={props.action as ActionPlayTile} />
        </Match>
        <Match when={props.action instanceof ActionSelectNewChain}>
          <NextGameActionSelectNewChain action={props.action as ActionSelectNewChain} />
        </Match>
        <Match when={props.action instanceof ActionSelectMergerSurvivor}>
          <NextGameActionSelectMergerSurvivor action={props.action as ActionSelectMergerSurvivor} />
        </Match>
        <Match when={props.action instanceof ActionSelectChainToDisposeOfNext}>
          <NextGameActionSelectChainToDisposeOfNext
            action={props.action as ActionSelectChainToDisposeOfNext}
          />
        </Match>
        <Match when={props.action instanceof ActionDisposeOfShares}>
          <NextGameActionDisposeOfShares action={props.action as ActionDisposeOfShares} />
        </Match>
        <Match when={props.action instanceof ActionPurchaseShares}>
          <NextGameActionPurchaseShares action={props.action as ActionPurchaseShares} />
        </Match>
        <Match when={props.action instanceof ActionGameOver}>Game over.</Match>
      </Switch>
    </div>
  );
}

function NextGameActionStartGame(props: { action: ActionStartGame }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      start the game.
    </>
  );
}

function NextGameActionPlayTile(props: { action: ActionPlayTile }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to play
      a tile.
    </>
  );
}

function NextGameActionSelectNewChain(props: { action: ActionSelectNewChain }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      select new chain (<NextGameActionHotelInitialsList chains={props.action.availableChains} />
      ).
    </>
  );
}

function NextGameActionSelectMergerSurvivor(props: { action: ActionSelectMergerSurvivor }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      select merger survivor (
      <NextGameActionHotelInitialsList chains={props.action.chainsBySize[0]} />
      ).
    </>
  );
}

function NextGameActionSelectChainToDisposeOfNext(props: {
  action: ActionSelectChainToDisposeOfNext;
}) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      select chain to dispose of next (
      <NextGameActionHotelInitialsList chains={props.action.defunctChains} />
      ).
    </>
  );
}

function NextGameActionDisposeOfShares(props: { action: ActionDisposeOfShares }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      dispose of <HotelName chain={props.action.defunctChain} /> shares.
    </>
  );
}

function NextGameActionPurchaseShares(props: { action: ActionPurchaseShares }) {
  return (
    <>
      Waiting for <Username username={props.action.game.usernames[props.action.playerId]} /> to
      purchase shares.
    </>
  );
}
