// src/client/pages/examples/EnableKeyboardShortcutsButton.tsx
import { createEffect, createSelector, createSignal } from 'solid-js';

let nextId = 0;
const [onlyEnabledId, setOnlyEnabledId] = createSignal(nextId++);
const isIdEnabled = createSelector(onlyEnabledId);

export function EnableKeyboardShortcutsButton(props: {
  onChangeEnabled: (enabled: boolean) => void;
}) {
  const myId = nextId++;

  createEffect(() => {
    props.onChangeEnabled(isIdEnabled(myId));
  });

  return (
    <input
      type="button"
      value={isIdEnabled(myId) ? 'Keyboard Shortcuts Enabled' : 'Enable Keyboard Shortcuts'}
      onClick={() => setOnlyEnabledId((id) => (id === myId ? 0 : myId))}
    />
  );
}

// src/routes/examples/EnableKeyboardShortcutsButton.svelte
<svelte:options immutable />

<script lang="ts" context="module">
  const onlyEnabledSymbolWritableStore = writable(Symbol());
</script>

<script lang="ts">
  import { writable } from 'svelte/store';

  export let enabled = false;

  const symbol = Symbol();

  $: enabled = symbol === $onlyEnabledSymbolWritableStore;
</script>

<input
  type="button"
  value={enabled ? 'Keyboard Shortcuts Enabled' : 'Enable Keyboard Shortcuts'}
  disabled={enabled}
  on:click={() => onlyEnabledSymbolWritableStore.set(symbol)}
/>
