// src/client/pages/examples/GameHistoryExamples.tsx
import { For } from 'solid-js';
import { GameState } from '../../../common/gameState';
import { GameHistory } from '../../components/GameHistory';
import styles from './GameHistoryExamples.module.css';
import { getExampleGame1, getExampleGame2, getExampleGameForGameHistory } from './games';

export function GameHistoryExamples() {
  const gameForGameHistory = getExampleGameForGameHistory();
  const game1 = getExampleGame1();
  const game2 = getExampleGame2();

  const allGameHistoryProps: {
    usernames: string[];
    gameStateHistory: GameState[];
    onMoveSelected: (index: number) => void;
  }[] = [
    {
      usernames: gameForGameHistory.usernames,
      gameStateHistory: gameForGameHistory.gameStateHistory,
      onMoveSelected,
    },
    {
      usernames: game1.usernames,
      gameStateHistory: game1.gameStateHistory,
      onMoveSelected,
    },
    {
      usernames: game2.usernames,
      gameStateHistory: game2.gameStateHistory,
      onMoveSelected,
    },
    {
      usernames: gameForGameHistory.usernames,
      gameStateHistory: [gameForGameHistory.gameStateHistory[0]],
      onMoveSelected,
    },
  ];

  function onMoveSelected(index: number) {
    console.log('onMoveSelected:', index);
  }

  return (
    <For each={allGameHistoryProps}>
      {(gameHistoryProps) => (
        <div class={styles.gameHistoryWrapper}>
          <GameHistory
            usernames={gameHistoryProps.usernames}
            gameStateHistory={gameHistoryProps.gameStateHistory}
            onMoveSelected={gameHistoryProps.onMoveSelected}
          />
        </div>
      )}
    </For>
  );
}

// src/routes/examples/GameHistoryExamples.svelte
<script lang="ts">
	import GameHistory from '$lib/GameHistory.svelte';
	import type { GameState } from '../../common/game';
	import { getExampleGame1, getExampleGame2, getExampleGameForGameHistory } from './games';

	const gameForGameHistory = getExampleGameForGameHistory();
	const game1 = getExampleGame1();
	const game2 = getExampleGame2();

	const allGameHistoryProps: {
		usernames: string[];
		gameStateHistory: GameState[];
		selectedMove?: number;
		onMoveSelected: (index: number) => void;
	}[] = [
		{
			usernames: gameForGameHistory.usernames,
			gameStateHistory: gameForGameHistory.gameStateHistory,
			onMoveSelected(index: number) {
				console.log('onMoveSelected:', index);
				allGameHistoryProps[0].selectedMove = index;
			},
		},
		{
			usernames: game1.usernames,
			gameStateHistory: game1.gameStateHistory,
			onMoveSelected(index: number) {
				console.log('onMoveSelected:', index);
				allGameHistoryProps[1].selectedMove = index;
			},
		},
		{
			usernames: game2.usernames,
			gameStateHistory: game2.gameStateHistory,
			onMoveSelected(index: number) {
				console.log('onMoveSelected:', index);
				allGameHistoryProps[2].selectedMove = index;
			},
		},
		{
			usernames: gameForGameHistory.usernames,
			gameStateHistory: [gameForGameHistory.gameStateHistory[0]],
			onMoveSelected(index: number) {
				console.log('onMoveSelected:', index);
				allGameHistoryProps[3].selectedMove = index;
			},
		},
	];
</script>

{#each allGameHistoryProps as gameHistoryProps}
	<p>
		<GameHistory
			usernames={gameHistoryProps.usernames}
			gameStateHistory={gameHistoryProps.gameStateHistory}
			selectedMove={gameHistoryProps.selectedMove}
			onMoveSelected={gameHistoryProps.onMoveSelected}
		/>
	</p>
{/each}

<style>
	p {
		height: 300px;
	}
</style>
